name: Build and Upload to Mail Retrieval App

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        python -m pip install --upgrade pip
        pip install uv

    - name: Sync environment with uv
      working-directory: mail_retrieval/
      run: |
        uv sync --frozen  # installs exactly as locked in uv.lock
        ls -la